-- CreateEnum
CREATE TYPE "JobApplicationStatus" AS ENUM ('APPLIED', 'REJECTED', 'INTERVIEW_COMPLETED', 'RECRUITER_OUTREACH', 'PHONE_INTERVIEW_COMPLETED', 'PHONE_SCREEN_COMPLETED', 'ROUND_2_COMPLETED', 'PHONE_SCREEN_PASSED', 'RECRUITER_SUBMITTED', 'PHONE_INTERVIEW_SCHEDULED', 'INTERVIEW_SCHEDULED', 'PHONE_SCREEN_SCHEDULED', 'ROUND_2_SCHEDULED', 'UNDER_REVIEW', 'OFFER_RECEIVED', 'OFFER_ACCEPTED', 'OFFER_DECLINED', 'WITHDRAWN');

-- CreateTable
CREATE TABLE "job_applications" (
    "id" SERIAL NOT NULL,
    "dateApplied" TIMESTAMP(3) NOT NULL,
    "company" TEXT NOT NULL,
    "jobTitle" TEXT NOT NULL,
    "status" "JobApplicationStatus" NOT NULL DEFAULT 'APPLIED',
    "contactName" TEXT,
    "contactEmail" TEXT,
    "jobUrl" TEXT,
    "notes" TEXT,
    "jobDescription" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "job_applications_pkey" PRIMARY KEY ("id")
);
