import { StyleSheet } from "@react-pdf/renderer";

export const colors = {
  violet: "#7C3AED",
  violetLight: "#A78BFA",
  violetBg: "#F5F3FF",
  dark: "#18181B",
  gray: "#71717A",
  grayLight: "#A1A1AA",
  grayBorder: "#E4E4E7",
  white: "#FFFFFF",
};

export const styles = StyleSheet.create({
  page: {
    fontFamily: "Helvetica",
    fontSize: 10,
    padding: 40,
    color: colors.dark,
    backgroundColor: colors.white,
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 30,
    paddingBottom: 20,
    borderBottomWidth: 2,
    borderBottomColor: colors.violet,
  },
  headerLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  logo: { width: 50, height: 50 },
  brandName: { fontSize: 18, fontFamily: "Helvetica-Bold", color: colors.dark },
  brandAccent: { color: colors.violet },
  tagline: { fontSize: 8, color: colors.grayLight, marginTop: 2, letterSpacing: 1 },
  headerRight: { alignItems: "flex-end" },
  docType: { fontSize: 24, fontFamily: "Helvetica-Bold", color: colors.violet, marginBottom: 4 },
  docNumber: { fontSize: 10, color: colors.gray },
  docDate: { fontSize: 10, color: colors.gray },
  infoRow: { flexDirection: "row", justifyContent: "space-between", marginBottom: 30 },
  infoBlock: { width: "48%" },
  infoLabel: { fontSize: 8, fontFamily: "Helvetica-Bold", color: colors.violet, textTransform: "uppercase", letterSpacing: 1.5, marginBottom: 8 },
  infoText: { fontSize: 10, color: colors.dark, marginBottom: 2 },
  infoTextLight: { fontSize: 10, color: colors.gray, marginBottom: 2 },
  table: { marginBottom: 30 },
  tableHeader: { flexDirection: "row", backgroundColor: colors.violet, paddingVertical: 8, paddingHorizontal: 12, borderRadius: 4 },
  tableHeaderText: { color: colors.white, fontFamily: "Helvetica-Bold", fontSize: 9, textTransform: "uppercase", letterSpacing: 0.5 },
  tableRow: { flexDirection: "row", paddingVertical: 10, paddingHorizontal: 12, borderBottomWidth: 1, borderBottomColor: colors.grayBorder },
  tableRowAlt: { backgroundColor: colors.violetBg },
  tableCell: { fontSize: 10, color: colors.dark },
  colDescription: { width: "50%" },
  colQty: { width: "10%", textAlign: "center" },
  colRate: { width: "20%", textAlign: "right" },
  colAmount: { width: "20%", textAlign: "right" },
  totalsContainer: { alignItems: "flex-end", marginBottom: 30 },
  totalsBox: { width: 250 },
  totalRow: { flexDirection: "row", justifyContent: "space-between", paddingVertical: 4 },
  totalLabel: { fontSize: 10, color: colors.gray },
  totalValue: { fontSize: 10, color: colors.dark, fontFamily: "Helvetica-Bold" },
  totalDivider: { borderBottomWidth: 1, borderBottomColor: colors.grayBorder, marginVertical: 4 },
  grandTotalRow: { flexDirection: "row", justifyContent: "space-between", paddingVertical: 8, backgroundColor: colors.violet, paddingHorizontal: 12, borderRadius: 4, marginTop: 4 },
  grandTotalLabel: { fontSize: 12, color: colors.white, fontFamily: "Helvetica-Bold" },
  grandTotalValue: { fontSize: 12, color: colors.white, fontFamily: "Helvetica-Bold" },
  section: { marginBottom: 20 },
  sectionTitle: { fontSize: 11, fontFamily: "Helvetica-Bold", color: colors.violet, marginBottom: 6 },
  sectionText: { fontSize: 9, color: colors.gray, lineHeight: 1.5 },
  footer: { position: "absolute", bottom: 30, left: 40, right: 40, flexDirection: "row", justifyContent: "space-between", alignItems: "center", paddingTop: 15, borderTopWidth: 1, borderTopColor: colors.grayBorder },
  footerText: { fontSize: 8, color: colors.grayLight },
  footerTagline: { fontSize: 8, color: colors.violet, fontFamily: "Helvetica-Bold", letterSpacing: 0.5 },
});
